In [2]:
import pandas as pd

In [5]:
gsheetid = "1JXhc5Ag8VEtsCmScDdJqEXYmY6FP8HIMNnRVjpTxIVE"
sheet_name = "Sheet1"
gsheet_url = f"https://docs.google.com/spreadsheets/d/{gsheetid}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
df = pd.read_csv(gsheet_url)
df.head()

,tanggal,kode,buy,lot_buy,conf_buy,sl,tp,%Risk,RpRisk,Equity Per Trade,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,5/26/2023,ASLC,104.0,29.0,1.0,102.0,116.0,"2,4%",7.308,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5/24/2023,AYLS,73.0,41.0,1.0,68.0,105.0,"7,3%",21.997,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5/28/2023,BABP,78.0,38.0,1.0,75.0,89.0,"4,3%",12.882,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5/25/2023,MTWI,92.0,33.0,1.0,85.0,98.0,"8,1%",24.618,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5/28/2023,MTWI,90.0,33.0,1.0,85.0,118.0,"6,1%",17.985,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN